#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Sonaro Gate • 2025.1 LTS  —  Automated Ubuntu 24.04 LTS Installer
# ─────────────────────────────────────────────────────────────────────────────
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/huynhtrungcsc/sonaro-gate/main/deploy/install.sh | sudo bash
#
#   Or clone the repo first:
#   git clone https://github.com/huynhtrungcsc/sonaro-gate.git
#   cd sonaro-gate && sudo bash deploy/install.sh
#
# What this script does:
#   1. Installs Node.js 20, PostgreSQL 16, iptables, networking tools
#   2. Creates a system user 'aegis' and installs files to /opt/sonaro
#   3. Creates the PostgreSQL database and user
#   4. Runs database migrations (drizzle-kit push)
#   5. Installs a systemd service (sonaro-gate.service)
#   6. Starts the service — first boot will launch the CLI setup wizard
#
# Tested on: Ubuntu 24.04 LTS (Noble Numbat)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
ok()      { echo -e "${GREEN}[  OK ]${RESET}  $*"; }
warn()    { echo -e "${YELLOW}[ WARN]${RESET}  $*"; }
die()     { echo -e "${RED}[ERROR]${RESET}  $*" >&2; exit 1; }

# ── Guards ────────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "This script must be run as root (sudo)."
[[ -f /etc/os-release ]] || die "Cannot detect OS."
source /etc/os-release
[[ "$ID" == "ubuntu" && "${VERSION_ID}" == "24.04" ]] \
    || warn "Tested on Ubuntu 24.04 — your OS is: $PRETTY_NAME"

INSTALL_DIR="${INSTALL_DIR:-/opt/sonaro}"
AEGIS_USER="sonaro"
DB_NAME="sonaro_gate"
DB_USER="aegis_db"
DB_PASS="$(openssl rand -hex 24)"
JWT_SECRET="$(openssl rand -hex 32)"
PORT="${PORT:-5000}"

echo -e ""
echo -e "${BOLD}${CYAN}"
echo -e "  ╔══════════════════════════════════════════════════════╗"
echo -e "  ║          SONARO GATE • 2025.1 LTS — Installer            ║"
echo -e "  ║          Ubuntu 24.04 LTS · Next-Gen Firewall        ║"
echo -e "  ╚══════════════════════════════════════════════════════╝"
echo -e "${RESET}"

# ── Step 1: System packages ───────────────────────────────────────────────────
info "Step 1/7 — Installing system dependencies..."
export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -y -qq \
    curl wget gnupg ca-certificates lsb-release \
    iptables iptables-persistent \
    iproute2 ipset \
    netplan.io \
    postgresql postgresql-client \
    git build-essential

# ── Step 2: Node.js 20 ───────────────────────────────────────────────────────
info "Step 2/7 — Installing Node.js 20..."
if ! command -v node &>/dev/null || [[ "$(node -v)" != v20* ]]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y -qq nodejs
fi
ok "Node.js $(node -v)"

# ── Step 3: Install application files ─────────────────────────────────────────
info "Step 3/7 — Installing Sonaro Gate to ${INSTALL_DIR}..."

# Create system user
if ! id "$AEGIS_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /bin/false "$AEGIS_USER"
fi

# Copy application
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_SRC="$(dirname "$SCRIPT_DIR")"   # parent of deploy/

mkdir -p "$INSTALL_DIR"
cp -r "$APP_SRC"/. "$INSTALL_DIR/"

# Install npm dependencies and build
cd "$INSTALL_DIR"
npm ci --omit=dev
npm run build

chown -R root:"$AEGIS_USER" "$INSTALL_DIR"
chmod -R 750 "$INSTALL_DIR"
ok "Application installed to ${INSTALL_DIR}"

# ── Step 4: Database ──────────────────────────────────────────────────────────
info "Step 4/7 — Configuring PostgreSQL..."
systemctl enable --now postgresql

sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';" 2>/dev/null || \
    sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASS}';"
sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" 2>/dev/null || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"
ok "PostgreSQL ready — database: ${DB_NAME}"

# ── Step 5: Environment file ──────────────────────────────────────────────────
info "Step 5/7 — Writing environment configuration..."
cat > "${INSTALL_DIR}/.env" <<EOF
# Sonaro Gate — Environment Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Regenerate JWT_SECRET with: openssl rand -hex 32

NODE_ENV=production
PORT=${PORT}
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=${JWT_SECRET}
SONARO_SKIP_SETUP=
EOF
chmod 640 "${INSTALL_DIR}/.env"
chown root:"$AEGIS_USER" "${INSTALL_DIR}/.env"

# ── Step 6: Database migrations ───────────────────────────────────────────────
info "Step 6/7 — Running database migrations..."
cd "$INSTALL_DIR"
DATABASE_URL="$DATABASE_URL" npx drizzle-kit push --force
DATABASE_URL="$DATABASE_URL" npx tsx server/seed.ts
ok "Database schema and seed data applied"

# ── Step 7: Systemd service ───────────────────────────────────────────────────
info "Step 7/7 — Installing systemd service..."
cp "${INSTALL_DIR}/deploy/sonaro-gate.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable sonaro-gate
systemctl start sonaro-gate
ok "Service sonaro-gate started"

# ── Done ──────────────────────────────────────────────────────────────────────
LAN_IP=$(ip route get 1 2>/dev/null | grep -oP 'src \K\S+' | head -1)

echo ""
echo -e "${BOLD}${GREEN}"
echo -e "  ╔══════════════════════════════════════════════════════╗"
echo -e "  ║                  INSTALLATION COMPLETE              ║"
echo -e "  ╚══════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo -e "  ${BOLD}Setup wizard:${RESET}  Run the interactive setup now:"
echo -e "               ${CYAN}sudo systemctl stop sonaro-gate${RESET}"
echo -e "               ${CYAN}sudo bash -c 'cd ${INSTALL_DIR} && npx tsx server/index.ts'${RESET}"
echo ""
echo -e "  ${BOLD}Web UI:${RESET}        http://${LAN_IP:-<LAN_IP>}:${PORT}"
echo -e "  ${BOLD}Login:${RESET}         admin@sonaro.local / Admin123!  (change on first login)"
echo ""
echo -e "  ${BOLD}Service:${RESET}"
echo -e "    Status: ${CYAN}systemctl status sonaro-gate${RESET}"
echo -e "    Logs:   ${CYAN}journalctl -u sonaro-gate -f${RESET}"
echo -e "    Restart:${CYAN}systemctl restart sonaro-gate${RESET}"
echo ""
echo -e "  Credentials written to: ${INSTALL_DIR}/.env"
echo ""
